# Generated by Django 3.2.25 on 2024-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Project', 'Project')], default='Blog', max_length=50),
        ),
    ]
